const actionTypes = Object.freeze({
    //APP
    CHANGE_LANGUAGE_SUSCESS: 'CHANGE_LANGUAGE_SUSCESS:',
    CHANGE_LANGUAGE_FAILED: 'CHANGE_LANGUAGE_FAILED',

    LOGIN_SYSTEM_SUSCESS: 'LOGIN_SYSTEM_SUSCESS:',
    LOGIN_SYSTEM_FAILED: 'LOGIN_SYSTEM_FAILED',
    
    REGISTER_SYSTEM_SUSCESS: 'REGISTER_SYSTEM_SUSCESS:',
    REGISTER_SYSTEM_FAILED: 'REGISTER_SYSTEM_FAILED',

    RETRIEVAL_PASSWORD_SUSCESS: 'RETRIEVAL_PASSWORD_SUSCESS:',
    RETRIEVAL_PASSWORD_FAILED: 'RETRIEVAL_PASSWORD_FAILED',

    UPDATE_PASSWORD_SUSCESS: 'UPDATE_PASSWORD_SUSCESS:',
    UPDATE_PASSWORD_FAILED: 'UPDATE_PASSWORD_FAILED',

    CREATE_USER_SUSCESS: 'CREATE_USER_SUSCESS:',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    GET_ALL_USER_SUSCESS: 'GET_ALL_USER_SUSCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',


    // ADMIN
    GET_DATA_ALLCODE_SUCCESS: 'GET_DATA_ALLCODE_SUCCESS',
    GET_DATE_ALLCODE_FAILED: 'GET_DATE_ALLCODE_FAILED',

    GET_DATA_PROVINCE_SUCCESS: 'GET_DATA_PROVINCE_SUCCESS',
    GET_DATE_PROVINCE_FAILED: 'GET_DATE_PROVINCE_FAILED',

    GET_DATA_WARDS_SUCCESS: 'GET_DATA_WARDS_SUCCESS',
    GET_DATE_WARDS_FAILED: 'GET_DATE_WARDS_FAILED',

    GET_ALL_SHOP_SUSCESS: 'GET_ALL_SHOP_SUSCESS',
    GET_ALL_SHOP_FAILED: 'GET_ALL_SHOP_FAILED',

    

})

export default actionTypes;