const actionTypes = Object.freeze({
    //APP
    CHANGE_LANGUAGE_SUSCESS: 'CHANGE_LANGUAGE_SUSCESS:',
    CHANGE_LANGUAGE_FAILED: 'CHANGE_LANGUAGE_FAILED',

    LOGIN_SYSTEM_SUSCESS: 'LOGIN_SYSTEM_SUSCESS:',
    LOGIN_SYSTEM_FAILED: 'LOGIN_SYSTEM_FAILED',
    
    REGISTER_SYSTEM_SUSCESS: 'REGISTER_SYSTEM_SUSCESS:',
    REGISTER_SYSTEM_FAILED: 'REGISTER_SYSTEM_FAILED',

    RETRIEVAL_PASSWORD_SUSCESS: 'RETRIEVAL_PASSWORD_SUSCESS:',
    RETRIEVAL_PASSWORD_FAILED: 'RETRIEVAL_PASSWORD_FAILED',

    UPDATE_PASSWORD_SUSCESS: 'UPDATE_PASSWORD_SUSCESS:',
    UPDATE_PASSWORD_FAILED: 'UPDATE_PASSWORD_FAILED',

    GET_ITEMS_LIKES: 'GET_ITEMS_LIKES',
    ADD_ITEMS_TO_CART: 'ADD_ITEMS_TO_CART',
    GET_ITEMS_CART: 'GET_ITEMS_CART',
    
    

    // ADMIN
    CREATE_USER_SUSCESS: 'CREATE_USER_SUSCESS:',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    GET_ALL_USER_SUSCESS: 'GET_ALL_USER_SUSCESS',
    GET_ALL_USER_NOT_SELLER_SUSCESS: 'GET_ALL_USER_NOT_SELLER_SUSCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',

    GET_DATA_ALLCODE_SUCCESS: 'GET_DATA_ALLCODE_SUCCESS',
    GET_DATE_ALLCODE_FAILED: 'GET_DATE_ALLCODE_FAILED',
    
    GET_DATA_PROVINCE_SUCCESS: 'GET_DATA_PROVINCE_SUCCESS',
    GET_DATE_PROVINCE_FAILED: 'GET_DATE_PROVINCE_FAILED',
    
    GET_DATA_WARDS_SUCCESS: 'GET_DATA_WARDS_SUCCESS',
    GET_DATE_WARDS_FAILED: 'GET_DATE_WARDS_FAILED',
    
    GET_ALL_SHOP_SUSCESS: 'GET_ALL_SHOP_SUSCESS',
    GET_ALL_SHOP_FAILED: 'GET_ALL_SHOP_FAILED',
    

    GET_ALL_CATEGORY_SUSCESS: 'GET_ALL_CATEGORY_SUSCESS',
    GET_ALL_CATEGORY_FAILED: 'GET_ALL_CATEGORY_FAILED',

    GET_DATA_ALLCODE_FSB_SUCCESS: 'GET_DATA_ALLCODE_FSB_SUCCESS',
    GET_DATA_ALLCODE_FSAM_SUCCESS: 'GET_DATA_ALLCODE_FSAM_SUCCESS',
    GET_DATA_ALLCODE_FSM_SUCCESS: 'GET_DATA_ALLCODE_FSM_SUCCESS',
    GET_DATA_ALLCODE_FSAW_SUCCESS: 'GET_DATA_ALLCODE_FSAW_SUCCESS',
    GET_DATA_ALLCODE_ALL_SUCCESS: 'GET_DATA_ALLCODE_ALL_SUCCESS',
    GET_DATA_ALLCODE_DCC_SUCCESS: 'GET_DATA_ALLCODE_DCC_SUCCESS',
    GET_DATA_ALLCODE_BNPRD_SUCCESS: 'GET_DATA_ALLCODE_BNPRD_SUCCESS',
    GET_DATA_ALLCODE_TYPESIZE_SUCCESS: 'GET_DATA_ALLCODE_TYPESIZE_SUCCESS',
    GET_DATA_ALLCODE_SIZE_SUCCESS:'GET_DATA_ALLCODE_SIZE_SUCCESS',
    GET_DATA_ALLCODE_SZNB_SUCCESS:'GET_DATA_ALLCODE_SZNB_SUCCESS',
    GET_DATA_ALLCODE_COLOR_SUCCESS: 'GET_DATA_ALLCODE_COLOR_SUCCESS',


    GET_DATA_ITEMS_SUCCESS: 'GET_DATA_ITEMS_SUCCESS',
    GET_DATA_ITEMS_FAILED: 'GET_DATA_ITEMS_FAILED',

    SET_VALUE_EMPTY: 'SET_VALUE_EMPTY',

    CHANGE_ITEMS_VOUCHER_SUCCESS: 'CHANGE_ITEMS_VOUCHER_SUCCESS',

    GET_NEW_DATA_VOUCHER: 'GET_NEW_DATA_VOUCHER',

    SET_EMPTY_DATA_LOG_OUT: 'SET_EMPTY_DATA_LOG_OUT',
    ADD_DATA_OPTIONS_SEARCH_NAV: 'ADD_DATA_OPTIONS_SEARCH_NAV',
    GET_ONE_ITEMS_SUCCESS: 'GET_ONE_ITEMS_SUCCESS',








})

export default actionTypes;